"""add_remaining_modules

Revision ID: 12b5d8f3f408
Revises: 4ca1d8de12a6
Create Date: 2026-07-29 16:45:52.895937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '12b5d8f3f408'
down_revision: Union[str, None] = '4ca1d8de12a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('reorder_threshold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_items')),
    sa.UniqueConstraint('name', name=op.f('uq_inventory_items_name'))
    )
    op.create_index(op.f('ix_inventory_items_category'), 'inventory_items', ['category'], unique=False)
    op.create_table('shelter_facilities',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shelter_facilities')),
    sa.UniqueConstraint('name', name=op.f('uq_shelter_facilities_name'))
    )
    op.create_table('grievance_tickets',
    sa.Column('reporter_name', sa.String(length=255), nullable=False),
    sa.Column('reporter_phone', sa.String(length=32), nullable=False),
    sa.Column('complaint_type', sa.String(length=128), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_to_admin_id', sa.UUID(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_admin_id'], ['users.id'], name=op.f('fk_grievance_tickets_assigned_to_admin_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grievance_tickets'))
    )
    op.create_index(op.f('ix_grievance_tickets_status'), 'grievance_tickets', ['status'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('moved_by', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], name=op.f('fk_inventory_movements_item_id_inventory_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moved_by'], ['users.id'], name=op.f('fk_inventory_movements_moved_by_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_movements'))
    )
    op.create_table('requisition_orders',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], name=op.f('fk_requisition_orders_item_id_inventory_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_requisition_orders_requester_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requisition_orders'))
    )
    op.create_index(op.f('ix_requisition_orders_status'), 'requisition_orders', ['status'], unique=False)
    op.create_table('shelter_sections',
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['shelter_facilities.id'], name=op.f('fk_shelter_sections_facility_id_shelter_facilities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shelter_sections'))
    )
    op.create_table('vehicles',
    sa.Column('make_model', sa.String(length=255), nullable=False),
    sa.Column('license_plate', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('primary_driver_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_driver_id'], ['users.id'], name=op.f('fk_vehicles_primary_driver_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles'))
    )
    op.create_index(op.f('ix_vehicles_license_plate'), 'vehicles', ['license_plate'], unique=True)
    op.create_table('equipment_checkouts',
    sa.Column('equipment_name', sa.String(length=255), nullable=False),
    sa.Column('assigned_to_agent_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_vehicle_id', sa.UUID(), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_agent_id'], ['users.id'], name=op.f('fk_equipment_checkouts_assigned_to_agent_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_vehicle_id'], ['vehicles.id'], name=op.f('fk_equipment_checkouts_assigned_to_vehicle_id_vehicles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_checkouts'))
    )
    op.create_table('fleet_maintenances',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_fleet_maintenances_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fleet_maintenances'))
    )
    op.create_table('kennels',
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.String(length=64), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('sanitation_state', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['shelter_sections.id'], name=op.f('fk_kennels_section_id_shelter_sections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kennels'))
    )
    op.create_table('clinical_exams',
    sa.Column('dog_id', sa.UUID(), nullable=False),
    sa.Column('vet_id', sa.UUID(), nullable=False),
    sa.Column('exam_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('body_condition_score', sa.Integer(), nullable=False),
    sa.Column('dental_health', sa.String(length=64), nullable=True),
    sa.Column('ocular_aural_notes', sa.Text(), nullable=True),
    sa.Column('coat_condition', sa.String(length=128), nullable=True),
    sa.Column('visible_injuries', sa.Text(), nullable=True),
    sa.Column('triage_diagnosis', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], name=op.f('fk_clinical_exams_dog_id_dog_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vet_id'], ['users.id'], name=op.f('fk_clinical_exams_vet_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_exams'))
    )
    op.create_table('daily_care_logs',
    sa.Column('dog_id', sa.UUID(), nullable=False),
    sa.Column('logged_by', sa.UUID(), nullable=False),
    sa.Column('feed_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dietary_requirements', sa.Text(), nullable=True),
    sa.Column('exercise_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('behavioral_enrichment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], name=op.f('fk_daily_care_logs_dog_id_dog_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], name=op.f('fk_daily_care_logs_logged_by_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_care_logs'))
    )
    op.create_table('facility_transfers',
    sa.Column('dog_id', sa.UUID(), nullable=False),
    sa.Column('from_facility_id', sa.UUID(), nullable=False),
    sa.Column('to_facility_id', sa.UUID(), nullable=False),
    sa.Column('transferred_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], name=op.f('fk_facility_transfers_dog_id_dog_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_facility_id'], ['shelter_facilities.id'], name=op.f('fk_facility_transfers_from_facility_id_shelter_facilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_facility_id'], ['shelter_facilities.id'], name=op.f('fk_facility_transfers_to_facility_id_shelter_facilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transferred_by'], ['users.id'], name=op.f('fk_facility_transfers_transferred_by_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facility_transfers'))
    )
    op.create_table('medical_treatments',
    sa.Column('dog_id', sa.UUID(), nullable=False),
    sa.Column('vet_id', sa.UUID(), nullable=False),
    sa.Column('treatment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('treatment_type', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('anesthesia_log', sa.Text(), nullable=True),
    sa.Column('post_op_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], name=op.f('fk_medical_treatments_dog_id_dog_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vet_id'], ['users.id'], name=op.f('fk_medical_treatments_vet_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_treatments'))
    )
    op.create_table('prescriptions',
    sa.Column('dog_id', sa.UUID(), nullable=False),
    sa.Column('vet_id', sa.UUID(), nullable=False),
    sa.Column('drug_name', sa.String(length=128), nullable=False),
    sa.Column('dosage', sa.String(length=128), nullable=False),
    sa.Column('route', sa.String(length=64), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], name=op.f('fk_prescriptions_dog_id_dog_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vet_id'], ['users.id'], name=op.f('fk_prescriptions_vet_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescriptions'))
    )
    op.create_table('vaccination_records',
    sa.Column('dog_id', sa.UUID(), nullable=False),
    sa.Column('administered_by', sa.UUID(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=128), nullable=False),
    sa.Column('administered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lot_number', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['administered_by'], ['users.id'], name=op.f('fk_vaccination_records_administered_by_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], name=op.f('fk_vaccination_records_dog_id_dog_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vaccination_records'))
    )
    op.create_table('service_feedbacks',
    sa.Column('rescue_case_id', sa.UUID(), nullable=True),
    sa.Column('adoption_application_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['adoption_application_id'], ['adoption_applications.id'], name=op.f('fk_service_feedbacks_adoption_application_id_adoption_applications'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rescue_case_id'], ['rescue_requests.id'], name=op.f('fk_service_feedbacks_rescue_case_id_rescue_requests'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_feedbacks'))
    )
    op.alter_column('dog_profiles', 'kennel_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using="kennel_id::uuid")
    op.create_foreign_key(op.f('fk_dog_profiles_shelter_facility_id_shelter_facilities'), 'dog_profiles', 'shelter_facilities', ['shelter_facility_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_dog_profiles_kennel_id_kennels'), 'dog_profiles', 'kennels', ['kennel_id'], ['id'], ondelete='SET NULL')
    op.add_column('report_matches', sa.Column('microchip_doc_url', sa.String(length=512), nullable=True))
    op.add_column('report_matches', sa.Column('vet_bill_url', sa.String(length=512), nullable=True))
    op.add_column('report_matches', sa.Column('photo_proof_url', sa.String(length=512), nullable=True))
    op.add_column('report_matches', sa.Column('verification_notes', sa.Text(), nullable=True))
    op.add_column('report_matches', sa.Column('claim_reviewed_by', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_report_matches_claim_reviewed_by_users'), 'report_matches', 'users', ['claim_reviewed_by'], ['id'], ondelete='SET NULL')
    op.add_column('rescue_requests', sa.Column('reporter_alternate_phone', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rescue_requests', 'reporter_alternate_phone')
    op.drop_constraint(op.f('fk_report_matches_claim_reviewed_by_users'), 'report_matches', type_='foreignkey')
    op.drop_column('report_matches', 'claim_reviewed_by')
    op.drop_column('report_matches', 'verification_notes')
    op.drop_column('report_matches', 'photo_proof_url')
    op.drop_column('report_matches', 'vet_bill_url')
    op.drop_column('report_matches', 'microchip_doc_url')
    op.drop_constraint(op.f('fk_dog_profiles_kennel_id_kennels'), 'dog_profiles', type_='foreignkey')
    op.drop_constraint(op.f('fk_dog_profiles_shelter_facility_id_shelter_facilities'), 'dog_profiles', type_='foreignkey')
    op.alter_column('dog_profiles', 'kennel_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.drop_table('service_feedbacks')
    op.drop_table('vaccination_records')
    op.drop_table('prescriptions')
    op.drop_table('medical_treatments')
    op.drop_table('facility_transfers')
    op.drop_table('daily_care_logs')
    op.drop_table('clinical_exams')
    op.drop_table('kennels')
    op.drop_table('fleet_maintenances')
    op.drop_table('equipment_checkouts')
    op.drop_index(op.f('ix_vehicles_license_plate'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_table('shelter_sections')
    op.drop_index(op.f('ix_requisition_orders_status'), table_name='requisition_orders')
    op.drop_table('requisition_orders')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_grievance_tickets_status'), table_name='grievance_tickets')
    op.drop_table('grievance_tickets')
    op.drop_table('shelter_facilities')
    op.drop_index(op.f('ix_inventory_items_category'), table_name='inventory_items')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
