"""add_core_modules

Revision ID: 4ca1d8de12a6
Revises: dadfa609e36a
Create Date: 2026-07-29 15:44:09.003950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4ca1d8de12a6'
down_revision: Union[str, None] = 'dadfa609e36a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rescue_requests',
    sa.Column('ticket_number', sa.String(length=64), nullable=False),
    sa.Column('reporter_name', sa.String(length=255), nullable=False),
    sa.Column('reporter_phone', sa.String(length=32), nullable=False),
    sa.Column('reporter_email', sa.String(length=255), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('location_address', sa.Text(), nullable=False),
    sa.Column('location_landmark', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('animal_count', sa.Integer(), nullable=False),
    sa.Column('physical_condition', sa.String(length=64), nullable=False),
    sa.Column('behavioral_indicators', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rejection_rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rescue_requests'))
    )
    op.create_index(op.f('ix_rescue_requests_status'), 'rescue_requests', ['status'], unique=False)
    op.create_index(op.f('ix_rescue_requests_ticket_number'), 'rescue_requests', ['ticket_number'], unique=True)
    op.create_table('volunteer_shifts',
    sa.Column('shelter_facility_id', sa.UUID(), nullable=True),
    sa.Column('role_name', sa.String(length=64), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volunteer_shifts'))
    )
    op.create_table('dog_profiles',
    sa.Column('registration_number', sa.String(length=64), nullable=False),
    sa.Column('rescue_case_id', sa.UUID(), nullable=True),
    sa.Column('microchip_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('breed', sa.String(length=128), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('is_spayed_neutered', sa.Boolean(), nullable=False),
    sa.Column('estimated_age', sa.String(length=64), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('temperament', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('shelter_facility_id', sa.UUID(), nullable=True),
    sa.Column('kennel_id', sa.String(length=64), nullable=True),
    sa.Column('is_adoptable', sa.Boolean(), nullable=False),
    sa.Column('is_quarantine_passed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rescue_case_id'], ['rescue_requests.id'], name=op.f('fk_dog_profiles_rescue_case_id_rescue_requests'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dog_profiles'))
    )
    op.create_index(op.f('ix_dog_profiles_microchip_id'), 'dog_profiles', ['microchip_id'], unique=True)
    op.create_index(op.f('ix_dog_profiles_registration_number'), 'dog_profiles', ['registration_number'], unique=True)
    op.create_index(op.f('ix_dog_profiles_status'), 'dog_profiles', ['status'], unique=False)
    op.create_table('donor_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tax_identifier', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_donor_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donor_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_donor_profiles_user_id'))
    )
    op.create_table('foster_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('active_count', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_foster_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_foster_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_foster_profiles_user_id'))
    )
    op.create_index(op.f('ix_foster_profiles_status'), 'foster_profiles', ['status'], unique=False)
    op.create_table('found_reports',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('breed_observed', sa.String(length=128), nullable=False),
    sa.Column('color_observed', sa.String(length=64), nullable=False),
    sa.Column('location_address', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('found_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_found_reports_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_found_reports'))
    )
    op.create_index(op.f('ix_found_reports_status'), 'found_reports', ['status'], unique=False)
    op.create_table('lost_reports',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pet_name', sa.String(length=255), nullable=False),
    sa.Column('breed', sa.String(length=128), nullable=False),
    sa.Column('color', sa.String(length=64), nullable=False),
    sa.Column('microchip_id', sa.String(length=64), nullable=True),
    sa.Column('location_address', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lost_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lost_reports_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lost_reports'))
    )
    op.create_index(op.f('ix_lost_reports_status'), 'lost_reports', ['status'], unique=False)
    op.create_table('rescue_dispatches',
    sa.Column('rescue_request_id', sa.UUID(), nullable=False),
    sa.Column('assigned_driver_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.String(length=64), nullable=True),
    sa.Column('equipment_details', sa.Text(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('located_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rescued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_driver_id'], ['users.id'], name=op.f('fk_rescue_dispatches_assigned_driver_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rescue_request_id'], ['rescue_requests.id'], name=op.f('fk_rescue_dispatches_rescue_request_id_rescue_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rescue_dispatches')),
    sa.UniqueConstraint('rescue_request_id', name=op.f('uq_rescue_dispatches_rescue_request_id'))
    )
    op.create_table('rescue_reports',
    sa.Column('rescue_request_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name=op.f('fk_rescue_reports_agent_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rescue_request_id'], ['rescue_requests.id'], name=op.f('fk_rescue_reports_rescue_request_id_rescue_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rescue_reports'))
    )
    op.create_table('volunteer_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=False),
    sa.Column('emergency_contact_phone', sa.String(length=32), nullable=False),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('availability', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_volunteer_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volunteer_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_volunteer_profiles_user_id'))
    )
    op.create_index(op.f('ix_volunteer_profiles_status'), 'volunteer_profiles', ['status'], unique=False)
    op.create_table('adoption_applications',
    sa.Column('dog_id', sa.UUID(), nullable=False),
    sa.Column('adopter_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('residential_status', sa.String(length=32), nullable=False),
    sa.Column('has_landlord_approval', sa.Boolean(), nullable=False),
    sa.Column('has_yard_fence', sa.Boolean(), nullable=False),
    sa.Column('household_members_count', sa.Integer(), nullable=False),
    sa.Column('existing_pets_medical_details', sa.Text(), nullable=True),
    sa.Column('pet_care_experience', sa.Text(), nullable=True),
    sa.Column('vetting_officer_notes', sa.Text(), nullable=True),
    sa.Column('home_inspection_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('home_inspection_notes', sa.Text(), nullable=True),
    sa.Column('adoption_agreement_url', sa.String(length=512), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['adopter_id'], ['users.id'], name=op.f('fk_adoption_applications_adopter_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], name=op.f('fk_adoption_applications_dog_id_dog_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adoption_applications'))
    )
    op.create_index(op.f('ix_adoption_applications_status'), 'adoption_applications', ['status'], unique=False)
    op.create_table('donations',
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('dog_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('donation_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], name=op.f('fk_donations_dog_id_dog_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['donor_id'], ['donor_profiles.id'], name=op.f('fk_donations_donor_id_donor_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donations')),
    sa.UniqueConstraint('transaction_id', name=op.f('uq_donations_transaction_id'))
    )
    op.create_index(op.f('ix_donations_status'), 'donations', ['status'], unique=False)
    op.create_table('foster_placements',
    sa.Column('foster_id', sa.UUID(), nullable=False),
    sa.Column('dog_id', sa.UUID(), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], name=op.f('fk_foster_placements_dog_id_dog_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['foster_id'], ['foster_profiles.id'], name=op.f('fk_foster_placements_foster_id_foster_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_foster_placements'))
    )
    op.create_table('report_matches',
    sa.Column('lost_report_id', sa.UUID(), nullable=False),
    sa.Column('found_report_id', sa.UUID(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['found_report_id'], ['found_reports.id'], name=op.f('fk_report_matches_found_report_id_found_reports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lost_report_id'], ['lost_reports.id'], name=op.f('fk_report_matches_lost_report_id_lost_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_matches'))
    )
    op.create_index(op.f('ix_report_matches_status'), 'report_matches', ['status'], unique=False)
    op.create_table('shift_attendances',
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('volunteer_id', sa.UUID(), nullable=False),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hours_logged', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['volunteer_shifts.id'], name=op.f('fk_shift_attendances_shift_id_volunteer_shifts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer_profiles.id'], name=op.f('fk_shift_attendances_volunteer_id_volunteer_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_attendances'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_attendances')
    op.drop_index(op.f('ix_report_matches_status'), table_name='report_matches')
    op.drop_table('report_matches')
    op.drop_table('foster_placements')
    op.drop_index(op.f('ix_donations_status'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_adoption_applications_status'), table_name='adoption_applications')
    op.drop_table('adoption_applications')
    op.drop_index(op.f('ix_volunteer_profiles_status'), table_name='volunteer_profiles')
    op.drop_table('volunteer_profiles')
    op.drop_table('rescue_reports')
    op.drop_table('rescue_dispatches')
    op.drop_index(op.f('ix_lost_reports_status'), table_name='lost_reports')
    op.drop_table('lost_reports')
    op.drop_index(op.f('ix_found_reports_status'), table_name='found_reports')
    op.drop_table('found_reports')
    op.drop_index(op.f('ix_foster_profiles_status'), table_name='foster_profiles')
    op.drop_table('foster_profiles')
    op.drop_table('donor_profiles')
    op.drop_index(op.f('ix_dog_profiles_status'), table_name='dog_profiles')
    op.drop_index(op.f('ix_dog_profiles_registration_number'), table_name='dog_profiles')
    op.drop_index(op.f('ix_dog_profiles_microchip_id'), table_name='dog_profiles')
    op.drop_table('dog_profiles')
    op.drop_table('volunteer_shifts')
    op.drop_index(op.f('ix_rescue_requests_ticket_number'), table_name='rescue_requests')
    op.drop_index(op.f('ix_rescue_requests_status'), table_name='rescue_requests')
    op.drop_table('rescue_requests')
    # ### end Alembic commands ###
