"""add before_state and after_state to auth_audit_logs

Revision ID: 4e1fa2c99247
Revises: d9e0f1a2b3c2
Create Date: 2026-08-03 15:38:36.139459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4e1fa2c99247'
down_revision: Union[str, None] = 'd9e0f1a2b3c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccine_protocols',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('default_interval_days', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vaccine_protocols')),
    sa.UniqueConstraint('name', name=op.f('uq_vaccine_protocols_name'))
    )
    op.create_table('recurring_subscriptions',
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('frequency', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('next_charge_date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donor_profiles.id'], name=op.f('fk_recurring_subscriptions_donor_id_donor_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurring_subscriptions'))
    )
    op.create_index(op.f('ix_recurring_subscriptions_donor_id'), 'recurring_subscriptions', ['donor_id'], unique=False)
    op.create_index(op.f('ix_recurring_subscriptions_status'), 'recurring_subscriptions', ['status'], unique=False)
    op.create_table('kennel_cleaning_logs',
    sa.Column('kennel_id', sa.UUID(), nullable=False),
    sa.Column('cleaned_by', sa.UUID(), nullable=False),
    sa.Column('cleaned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sanitation_state_after', sa.String(length=32), nullable=False),
    sa.Column('cleaning_method', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cleaned_by'], ['users.id'], name=op.f('fk_kennel_cleaning_logs_cleaned_by_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kennel_id'], ['kennels.id'], name=op.f('fk_kennel_cleaning_logs_kennel_id_kennels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kennel_cleaning_logs'))
    )
    op.create_table('rescue_dispatch_agents',
    sa.Column('dispatch_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name=op.f('fk_rescue_dispatch_agents_agent_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dispatch_id'], ['rescue_dispatches.id'], name=op.f('fk_rescue_dispatch_agents_dispatch_id_rescue_dispatches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rescue_dispatch_agents')),
    sa.UniqueConstraint('dispatch_id', 'agent_id', name='uq_rescue_dispatch_agents_dispatch_agent')
    )
    op.create_index(op.f('ix_rescue_dispatch_agents_agent_id'), 'rescue_dispatch_agents', ['agent_id'], unique=False)
    op.create_index(op.f('ix_rescue_dispatch_agents_dispatch_id'), 'rescue_dispatch_agents', ['dispatch_id'], unique=False)
    op.create_table('medical_clearances',
    sa.Column('dog_id', sa.UUID(), nullable=False),
    sa.Column('authorized_by_id', sa.UUID(), nullable=False),
    sa.Column('clearance_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['authorized_by_id'], ['users.id'], name=op.f('fk_medical_clearances_authorized_by_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], name=op.f('fk_medical_clearances_dog_id_dog_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_clearances'))
    )
    op.create_table('adoption_follow_ups',
    sa.Column('adoption_application_id', sa.UUID(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('media_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['adoption_application_id'], ['adoption_applications.id'], name=op.f('fk_adoption_follow_ups_adoption_application_id_adoption_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adoption_follow_ups'))
    )
    op.create_index(op.f('ix_adoption_follow_ups_adoption_application_id'), 'adoption_follow_ups', ['adoption_application_id'], unique=False)
    op.create_index(op.f('ix_adoption_follow_ups_status'), 'adoption_follow_ups', ['status'], unique=False)
    op.create_table('medication_administration_logs',
    sa.Column('prescription_id', sa.UUID(), nullable=True),
    sa.Column('dog_id', sa.UUID(), nullable=False),
    sa.Column('medication_name', sa.String(length=128), nullable=False),
    sa.Column('dosage', sa.String(length=128), nullable=False),
    sa.Column('route', sa.String(length=64), nullable=False),
    sa.Column('administered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('administered_by_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['administered_by_id'], ['users.id'], name=op.f('fk_medication_administration_logs_administered_by_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dog_id'], ['dog_profiles.id'], name=op.f('fk_medication_administration_logs_dog_id_dog_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('fk_medication_administration_logs_prescription_id_prescriptions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medication_administration_logs'))
    )
    op.add_column('adoption_applications', sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('auth_audit_logs', sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('auth_audit_logs', sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('uq_blog_posts_slug'), 'blog_posts', type_='unique')
    op.add_column('donations', sa.Column('recurring_subscription_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_donations_recurring_subscription_id'), 'donations', ['recurring_subscription_id'], unique=False)
    op.create_foreign_key(op.f('fk_donations_recurring_subscription_id_recurring_subscriptions'), 'donations', 'recurring_subscriptions', ['recurring_subscription_id'], ['id'], ondelete='SET NULL')
    op.add_column('equipment_checkouts', sa.Column('expected_return_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_equipment_checkouts_expected_return_at'), 'equipment_checkouts', ['expected_return_at'], unique=False)
    op.drop_constraint(op.f('uq_legal_documents_slug'), 'legal_documents', type_='unique')
    op.add_column('rescue_dispatches', sa.Column('assigned_vehicle_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_rescue_dispatches_assigned_vehicle_id'), 'rescue_dispatches', ['assigned_vehicle_id'], unique=False)
    op.create_foreign_key(op.f('fk_rescue_dispatches_assigned_vehicle_id_vehicles'), 'rescue_dispatches', 'vehicles', ['assigned_vehicle_id'], ['id'], ondelete='SET NULL')
    op.add_column('shelter_sections', sa.Column('section_type', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_shelter_sections_section_type'), 'shelter_sections', ['section_type'], unique=False)
    op.add_column('vehicles', sa.Column('vehicle_type', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_vehicles_vehicle_type'), 'vehicles', ['vehicle_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_vehicle_type'), table_name='vehicles')
    op.drop_column('vehicles', 'vehicle_type')
    op.drop_index(op.f('ix_shelter_sections_section_type'), table_name='shelter_sections')
    op.drop_column('shelter_sections', 'section_type')
    op.drop_constraint(op.f('fk_rescue_dispatches_assigned_vehicle_id_vehicles'), 'rescue_dispatches', type_='foreignkey')
    op.drop_index(op.f('ix_rescue_dispatches_assigned_vehicle_id'), table_name='rescue_dispatches')
    op.drop_column('rescue_dispatches', 'assigned_vehicle_id')
    op.create_unique_constraint(op.f('uq_legal_documents_slug'), 'legal_documents', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_equipment_checkouts_expected_return_at'), table_name='equipment_checkouts')
    op.drop_column('equipment_checkouts', 'expected_return_at')
    op.drop_constraint(op.f('fk_donations_recurring_subscription_id_recurring_subscriptions'), 'donations', type_='foreignkey')
    op.drop_index(op.f('ix_donations_recurring_subscription_id'), table_name='donations')
    op.drop_column('donations', 'recurring_subscription_id')
    op.create_unique_constraint(op.f('uq_blog_posts_slug'), 'blog_posts', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_column('auth_audit_logs', 'after_state')
    op.drop_column('auth_audit_logs', 'before_state')
    op.drop_column('adoption_applications', 'fee_amount')
    op.drop_table('medication_administration_logs')
    op.drop_index(op.f('ix_adoption_follow_ups_status'), table_name='adoption_follow_ups')
    op.drop_index(op.f('ix_adoption_follow_ups_adoption_application_id'), table_name='adoption_follow_ups')
    op.drop_table('adoption_follow_ups')
    op.drop_table('medical_clearances')
    op.drop_index(op.f('ix_rescue_dispatch_agents_dispatch_id'), table_name='rescue_dispatch_agents')
    op.drop_index(op.f('ix_rescue_dispatch_agents_agent_id'), table_name='rescue_dispatch_agents')
    op.drop_table('rescue_dispatch_agents')
    op.drop_table('kennel_cleaning_logs')
    op.drop_index(op.f('ix_recurring_subscriptions_status'), table_name='recurring_subscriptions')
    op.drop_index(op.f('ix_recurring_subscriptions_donor_id'), table_name='recurring_subscriptions')
    op.drop_table('recurring_subscriptions')
    op.drop_table('vaccine_protocols')
    # ### end Alembic commands ###
