"""reconcile_schema_drift

Closes a batch of model/migration gaps found by comparing every SQLAlchemy
model against the actual migration chain (same class of bug as
b2e6f4a1c9d7_add_stored_files_table):

- alembic/env.py never imported `pawguard.modules.settings.models`, so
  autogenerate/migrations could never see SystemSetting, PasswordPolicy, or
  BusinessRule at all. `password_policies` and `business_rules` were never
  created, and `system_settings` was missing columns (category,
  is_encrypted, is_editable) added to the model after its initial migration.
- `NotificationPreference` (notifications module) had no backing table.
- `deleted_at` (SoftDeleteMixin) was missing on clinical_exams,
  inventory_items, medical_treatments, notifications, prescriptions,
  vaccination_records, and vehicles even though their models mix in
  SoftDeleteMixin.
- `species` (lost_reports/found_reports), `notification_type`/`is_broadcast`/
  `action_url`/`sent_at` (notifications), and `status`/`facility_type`
  (shelter_facilities) were added to models but never migrated.

Revision ID: 783f541d2d75
Revises: d5f6a7b8c9e0
Create Date: 2026-07-30 21:44:00.920077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '783f541d2d75'
down_revision: Union[str, None] = 'd5f6a7b8c9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_rules',
    sa.Column('rule_key', sa.String(length=255), nullable=False),
    sa.Column('rule_value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_rules'))
    )
    op.create_index(op.f('ix_business_rules_module'), 'business_rules', ['module'], unique=False)
    op.create_index(op.f('ix_business_rules_rule_key'), 'business_rules', ['rule_key'], unique=True)
    op.create_table('password_policies',
    sa.Column('min_length', sa.Integer(), nullable=False),
    sa.Column('require_uppercase', sa.Boolean(), nullable=False),
    sa.Column('require_lowercase', sa.Boolean(), nullable=False),
    sa.Column('require_digit', sa.Boolean(), nullable=False),
    sa.Column('require_special_char', sa.Boolean(), nullable=False),
    sa.Column('max_age_days', sa.Integer(), nullable=False),
    sa.Column('password_history_count', sa.Integer(), nullable=False),
    sa.Column('max_login_attempts', sa.Integer(), nullable=False),
    sa.Column('lockout_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_policies'))
    )
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('enable_push', sa.Boolean(), nullable=False),
    sa.Column('enable_email', sa.Boolean(), nullable=False),
    sa.Column('enable_sms', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preferences')),
    sa.UniqueConstraint('user_id', name=op.f('uq_notification_preferences_user_id'))
    )
    op.add_column('clinical_exams', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('found_reports', sa.Column('species', sa.String(length=32), server_default=sa.text("'dog'"), nullable=False))
    op.create_index(op.f('ix_found_reports_species'), 'found_reports', ['species'], unique=False)
    op.add_column('inventory_items', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lost_reports', sa.Column('species', sa.String(length=32), server_default=sa.text("'dog'"), nullable=False))
    op.create_index(op.f('ix_lost_reports_species'), 'lost_reports', ['species'], unique=False)
    op.add_column('medical_treatments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('notification_type', sa.String(length=64), nullable=True))
    op.add_column('notifications', sa.Column('is_broadcast', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('notifications', sa.Column('action_url', sa.String(length=512), nullable=True))
    op.add_column('notifications', sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('notifications', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.add_column('prescriptions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('shelter_facilities', sa.Column('status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False))
    op.add_column('shelter_facilities', sa.Column('facility_type', sa.String(length=32), server_default=sa.text("'shelter'"), nullable=False))
    op.create_index(op.f('ix_shelter_facilities_facility_type'), 'shelter_facilities', ['facility_type'], unique=False)
    op.create_index(op.f('ix_shelter_facilities_status'), 'shelter_facilities', ['status'], unique=False)
    op.add_column('system_settings', sa.Column('category', sa.String(length=64), server_default=sa.text("'general'"), nullable=False))
    op.add_column('system_settings', sa.Column('is_encrypted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('system_settings', sa.Column('is_editable', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.alter_column('system_settings', 'key',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('system_settings', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_system_settings_category'), 'system_settings', ['category'], unique=False)
    op.add_column('vaccination_records', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vehicles', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'deleted_at')
    op.drop_column('vaccination_records', 'deleted_at')
    op.drop_index(op.f('ix_system_settings_category'), table_name='system_settings')
    op.alter_column('system_settings', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('system_settings', 'key',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.drop_column('system_settings', 'is_editable')
    op.drop_column('system_settings', 'is_encrypted')
    op.drop_column('system_settings', 'category')
    op.drop_index(op.f('ix_shelter_facilities_status'), table_name='shelter_facilities')
    op.drop_index(op.f('ix_shelter_facilities_facility_type'), table_name='shelter_facilities')
    op.drop_column('shelter_facilities', 'facility_type')
    op.drop_column('shelter_facilities', 'status')
    op.drop_column('prescriptions', 'deleted_at')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_column('notifications', 'deleted_at')
    op.drop_column('notifications', 'sent_at')
    op.drop_column('notifications', 'action_url')
    op.drop_column('notifications', 'is_broadcast')
    op.drop_column('notifications', 'notification_type')
    op.drop_column('medical_treatments', 'deleted_at')
    op.drop_index(op.f('ix_lost_reports_species'), table_name='lost_reports')
    op.drop_column('lost_reports', 'species')
    op.drop_column('inventory_items', 'deleted_at')
    op.drop_index(op.f('ix_found_reports_species'), table_name='found_reports')
    op.drop_column('found_reports', 'species')
    op.drop_column('clinical_exams', 'deleted_at')
    op.drop_table('notification_preferences')
    op.drop_table('password_policies')
    op.drop_index(op.f('ix_business_rules_rule_key'), table_name='business_rules')
    op.drop_index(op.f('ix_business_rules_module'), table_name='business_rules')
    op.drop_table('business_rules')
    # ### end Alembic commands ###
