"""add_composite_indexes_for_scalability

Revision ID: 84a0660c2de3
Revises: 70ebffe9001d
Create Date: 2026-08-17 10:29:44.959588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '84a0660c2de3'
down_revision: Union[str, None] = '70ebffe9001d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_auth_audit_logs_user_id_created_at', 'auth_audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_dog_profiles_status_shelter_facility_id', 'dog_profiles', ['status', 'shelter_facility_id'], unique=False)
    op.create_index('ix_dog_profiles_status_is_adoptable', 'dog_profiles', ['status', 'is_adoptable'], unique=False)
    op.create_index('ix_general_ledger_entries_account_id_entry_date', 'general_ledger_entries', ['account_id', 'entry_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_general_ledger_entries_account_id_entry_date', table_name='general_ledger_entries')
    op.drop_index('ix_dog_profiles_status_is_adoptable', table_name='dog_profiles')
    op.drop_index('ix_dog_profiles_status_shelter_facility_id', table_name='dog_profiles')
    op.drop_index('ix_auth_audit_logs_user_id_created_at', table_name='auth_audit_logs')
    # ### end Alembic commands ###
